base_url = "https://micouy.github.io"

compile_sass = true
highlight_code = true
build_search_index = false
output_dir = "docs"

[markdown]
highlight_code = true
highlight_theme = "nord"

[extra]
github = "https://github.com/micouy"
